version: '3.6'

services:

  truffle:
    container_name: development-truffle
    image: europe-west1-docker.pkg.dev/breadcrumbs-345213/breadcrumbs/development/truffle:latest
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/truffle/Dockerfile
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' ganache:8545
      interval: 5s
      timeout: 5s
      retries: 5
    tty: true
    env_file:
      - ../../../.env.development
    entrypoint: ./truffle-dev.sh
    volumes:
      - abis-volume:/backend/abis
    
  truffle-test:
    container_name: development-truffle-test
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/truffle/Dockerfile
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' ganache:8545
      interval: 5s
      timeout: 5s
      retries: 5
    entrypoint: ./truffle-test.sh

  postgres:
    image: postgres:10.6-alpine
    container_name: development-postgres
    env_file:
      - ../../../.env.development
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: development-pgadmin
    env_file:
      - ../../../.env.development
    depends_on:
      - postgres
    ports:
      - 5500:80

  prisma:
    container_name: development-prisma
    image: europe-west1-docker.pkg.dev/breadcrumbs-345213/breadcrumbs/development/prisma:latest
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/prisma/Dockerfile
    env_file:
      - ../../../.env.development

volumes:
  postgres-volume:
  abis-volume:
