version: '3.6'

services:
  ganache:
    container_name: production-ganache
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/ganache/Dockerfile
    ports:
      - 8545:8545

  truffle:
    container_name: production-truffle
    image: europe-west1-docker.pkg.dev/breadcrumbs-345213/breadcrumbs/production/truffle:latest
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/truffle/Dockerfile
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' ganache:8545
      interval: 5s
      timeout: 5s
      retries: 5
    tty: true
    volumes:
      - abis-volume:/backend/abis
    depends_on:
      - ganache

  postgres:
    image: postgres:10.6-alpine
    container_name: production-postgres
    env_file:
      - ../../../.env.production
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  prisma:
    container_name: production-prisma
    image: europe-west1-docker.pkg.dev/breadcrumbs-345213/breadcrumbs/production/prisma:latest
    build:
      context: ../../../
      dockerfile: ./deploy/docker/images/prisma/Dockerfile
    env_file:
      - ../../../.env.production
    depends_on:
      - ganache

volumes:
  postgres-volume:
  abis-volume:
